POST http://localhost:8080/api/atleta/adicionar-em-lote
Content-Type: application/json

[
  {
    "nome": "Andres",
    "sobrenome": "Martins",
    "dataDeNascimento": "2001-12-10",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1991-05-03",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2002-01-12",
    "nacionalidade": "Francês",
    "posicao": "PD",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Sebastián",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1998-03-22",
    "nacionalidade": "Uruguaio",
    "posicao": "LE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Clinton",
    "sobrenome": "Martins",
    "dataDeNascimento": "1993-01-12",
    "nacionalidade": "Camaronês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Angel",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2005-09-03",
    "nacionalidade": "Argentino",
    "posicao": "GOL",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Souza",
    "dataDeNascimento": "1989-03-03",
    "nacionalidade": "Português",
    "posicao": "LD",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Barros",
    "dataDeNascimento": "1995-01-23",
    "nacionalidade": "Croata",
    "posicao": "ATA",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1995-10-07",
    "nacionalidade": "Nigeriano",
    "posicao": "LE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "2000-08-12",
    "nacionalidade": "Camaronês",
    "posicao": "PE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Silva",
    "dataDeNascimento": "2001-01-21",
    "nacionalidade": "Português",
    "posicao": "ADE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Clinton",
    "sobrenome": "Silva",
    "dataDeNascimento": "1995-11-03",
    "nacionalidade": "Camaronês",
    "posicao": "PD",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1998-02-16",
    "nacionalidade": "Senegalês",
    "posicao": "LE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Martins",
    "dataDeNascimento": "1986-08-11",
    "nacionalidade": "Croata",
    "posicao": "PE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Dias",
    "dataDeNascimento": "1986-05-15",
    "nacionalidade": "Uruguaio",
    "posicao": "LE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Gabriel",
    "sobrenome": "Dias",
    "dataDeNascimento": "1989-07-08",
    "nacionalidade": "Brasileiro",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2004-05-18",
    "nacionalidade": "Português",
    "posicao": "ATA",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Barros",
    "dataDeNascimento": "1998-01-01",
    "nacionalidade": "Argentino",
    "posicao": "LD",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Peter",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2004-09-25",
    "nacionalidade": "Nigeriano",
    "posicao": "GOL",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1993-10-06",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Souza",
    "dataDeNascimento": "1989-12-09",
    "nacionalidade": "Italiano",
    "posicao": "ATA",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Vincent",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2005-05-13",
    "nacionalidade": "Camaronês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Barros",
    "dataDeNascimento": "2003-07-11",
    "nacionalidade": "Italiano",
    "posicao": "MEI",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Costa",
    "dataDeNascimento": "1992-03-06",
    "nacionalidade": "Espanhol",
    "posicao": "LE",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1990-06-03",
    "nacionalidade": "Uruguaio",
    "posicao": "VOL",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Barros",
    "dataDeNascimento": "1990-11-08",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1992-06-10",
    "nacionalidade": "Uruguaio",
    "posicao": "PD",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1992-11-20",
    "nacionalidade": "Senegalês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Thiago",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2001-10-01",
    "nacionalidade": "Brasileiro",
    "posicao": "MEI",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2002-07-28",
    "nacionalidade": "Senegalês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1999-06-08",
    "nacionalidade": "Alemão",
    "posicao": "ADE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Vincent",
    "sobrenome": "Gomes",
    "dataDeNascimento": "2004-03-24",
    "nacionalidade": "Camaronês",
    "posicao": "LD",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Santos",
    "dataDeNascimento": "2000-01-24",
    "nacionalidade": "Uruguaio",
    "posicao": "ADE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Silva",
    "dataDeNascimento": "2000-02-24",
    "nacionalidade": "Argentino",
    "posicao": "GOL",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Barros",
    "dataDeNascimento": "2003-10-11",
    "nacionalidade": "Nigeriano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Lionel",
    "sobrenome": "Silva",
    "dataDeNascimento": "2000-09-26",
    "nacionalidade": "Argentino",
    "posicao": "PE",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Vincent",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1995-04-25",
    "nacionalidade": "Camaronês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1989-02-21",
    "nacionalidade": "Francês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Marco",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1991-02-04",
    "nacionalidade": "Italiano",
    "posicao": "PE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2003-11-05",
    "nacionalidade": "Chileno",
    "posicao": "GOL",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Santos",
    "dataDeNascimento": "1985-01-22",
    "nacionalidade": "Português",
    "posicao": "PD",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1988-11-16",
    "nacionalidade": "Argentino",
    "posicao": "ATA",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Thiago",
    "sobrenome": "Henrique",
    "dataDeNascimento": "2005-02-16",
    "nacionalidade": "Brasileiro",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Rigobert",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1987-06-25",
    "nacionalidade": "Camaronês",
    "posicao": "PD",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1997-11-01",
    "nacionalidade": "Croata",
    "posicao": "ADE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Martins",
    "dataDeNascimento": "2004-07-18",
    "nacionalidade": "Senegalês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1989-08-08",
    "nacionalidade": "Português",
    "posicao": "LE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1992-03-01",
    "nacionalidade": "Chileno",
    "posicao": "ADE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1988-06-28",
    "nacionalidade": "Alemão",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Santos",
    "dataDeNascimento": "1994-01-21",
    "nacionalidade": "Nigeriano",
    "posicao": "GOL",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Santos",
    "dataDeNascimento": "2001-02-06",
    "nacionalidade": "Senegalês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1997-06-07",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2000-09-07",
    "nacionalidade": "Chileno",
    "posicao": "ADE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Marco",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1992-03-07",
    "nacionalidade": "Italiano",
    "posicao": "PD",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1994-02-02",
    "nacionalidade": "Croata",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Santos",
    "dataDeNascimento": "1990-07-15",
    "nacionalidade": "Senegalês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Costa",
    "dataDeNascimento": "1998-08-20",
    "nacionalidade": "Francês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1985-01-27",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1993-08-12",
    "nacionalidade": "Croata",
    "posicao": "MEI",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1990-05-18",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Rafael",
    "sobrenome": "Souza",
    "dataDeNascimento": "1986-10-14",
    "nacionalidade": "Brasileiro",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "John",
    "sobrenome": "Costa",
    "dataDeNascimento": "1991-06-01",
    "nacionalidade": "Nigeriano",
    "posicao": "PE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Barros",
    "dataDeNascimento": "2005-03-25",
    "nacionalidade": "Francês",
    "posicao": "LD",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "André",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1993-03-13",
    "nacionalidade": "Camaronês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "André",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1999-12-05",
    "nacionalidade": "Camaronês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1985-01-12",
    "nacionalidade": "Italiano",
    "posicao": "VOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Clinton",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1996-02-26",
    "nacionalidade": "Camaronês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1985-09-02",
    "nacionalidade": "Português",
    "posicao": "LE",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1992-07-23",
    "nacionalidade": "Croata",
    "posicao": "VOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Lorenzo",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1994-07-02",
    "nacionalidade": "Italiano",
    "posicao": "MEI",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Nicolas",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1986-10-15",
    "nacionalidade": "Argentino",
    "posicao": "LD",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Peter",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1987-05-26",
    "nacionalidade": "Nigeriano",
    "posicao": "PD",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Sadio",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1985-12-17",
    "nacionalidade": "Senegalês",
    "posicao": "LD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Sebastián",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1996-06-03",
    "nacionalidade": "Uruguaio",
    "posicao": "GOL",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1994-12-10",
    "nacionalidade": "Croata",
    "posicao": "PE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Barros",
    "dataDeNascimento": "1997-09-06",
    "nacionalidade": "Português",
    "posicao": "ADE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1988-12-07",
    "nacionalidade": "Croata",
    "posicao": "PD",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2001-04-18",
    "nacionalidade": "Uruguaio",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1992-07-09",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Santos",
    "dataDeNascimento": "2005-07-08",
    "nacionalidade": "Uruguaio",
    "posicao": "LE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Diego",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1985-08-03",
    "nacionalidade": "Uruguaio",
    "posicao": "LE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1998-09-07",
    "nacionalidade": "Francês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1996-11-28",
    "nacionalidade": "Italiano",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1985-09-10",
    "nacionalidade": "Uruguaio",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Souza",
    "dataDeNascimento": "1991-07-21",
    "nacionalidade": "Uruguaio",
    "posicao": "PE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "João",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2003-12-18",
    "nacionalidade": "Português",
    "posicao": "LE",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "David",
    "sobrenome": "Souza",
    "dataDeNascimento": "1992-01-28",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1992-04-19",
    "nacionalidade": "Brasileiro",
    "posicao": "ADE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Souza",
    "dataDeNascimento": "1989-05-09",
    "nacionalidade": "Croata",
    "posicao": "PE",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Henrique",
    "dataDeNascimento": "2000-09-02",
    "nacionalidade": "Chileno",
    "posicao": "LD",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1994-07-10",
    "nacionalidade": "Italiano",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Souza",
    "dataDeNascimento": "1985-01-21",
    "nacionalidade": "Nigeriano",
    "posicao": "PE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Rigobert",
    "sobrenome": "Barros",
    "dataDeNascimento": "1985-06-05",
    "nacionalidade": "Camaronês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Souza",
    "dataDeNascimento": "2002-05-25",
    "nacionalidade": "Brasileiro",
    "posicao": "VOL",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Sadio",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2005-09-03",
    "nacionalidade": "Senegalês",
    "posicao": "PD",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Souza",
    "dataDeNascimento": "1990-01-12",
    "nacionalidade": "Nigeriano",
    "posicao": "LD",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Dias",
    "dataDeNascimento": "1999-12-19",
    "nacionalidade": "Chileno",
    "posicao": "LE",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1999-07-01",
    "nacionalidade": "Senegalês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1988-09-03",
    "nacionalidade": "Francês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "2005-02-20",
    "nacionalidade": "Alemão",
    "posicao": "ATA",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Santos",
    "dataDeNascimento": "2003-11-14",
    "nacionalidade": "Português",
    "posicao": "MEI",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Niklas",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "2000-11-13",
    "nacionalidade": "Alemão",
    "posicao": "ADE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Dias",
    "dataDeNascimento": "2001-11-26",
    "nacionalidade": "Italiano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Barros",
    "dataDeNascimento": "1992-12-24",
    "nacionalidade": "Francês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Santos",
    "dataDeNascimento": "1995-08-25",
    "nacionalidade": "Italiano",
    "posicao": "PE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1997-11-18",
    "nacionalidade": "Português",
    "posicao": "ATA",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1990-05-23",
    "nacionalidade": "Argentino",
    "posicao": "LD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1996-02-11",
    "nacionalidade": "Uruguaio",
    "posicao": "LE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Henrique",
    "dataDeNascimento": "2000-07-12",
    "nacionalidade": "Uruguaio",
    "posicao": "PD",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Niklas",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1998-09-10",
    "nacionalidade": "Alemão",
    "posicao": "PD",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1996-09-25",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Silva",
    "dataDeNascimento": "1985-09-05",
    "nacionalidade": "Português",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Santos",
    "dataDeNascimento": "1988-08-22",
    "nacionalidade": "Italiano",
    "posicao": "PE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Timo",
    "sobrenome": "Barros",
    "dataDeNascimento": "2003-10-28",
    "nacionalidade": "Alemão",
    "posicao": "PD",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "John",
    "sobrenome": "Souza",
    "dataDeNascimento": "1991-03-12",
    "nacionalidade": "Nigeriano",
    "posicao": "PD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Gonzalo",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1992-07-14",
    "nacionalidade": "Argentino",
    "posicao": "VOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Luka",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1998-05-03",
    "nacionalidade": "Croata",
    "posicao": "ADE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1994-12-28",
    "nacionalidade": "Senegalês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Souza",
    "dataDeNascimento": "2003-08-25",
    "nacionalidade": "Espanhol",
    "posicao": "GOL",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Martins",
    "dataDeNascimento": "1999-11-23",
    "nacionalidade": "Senegalês",
    "posicao": "LE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "2000-08-21",
    "nacionalidade": "Espanhol",
    "posicao": "GOL",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Dias",
    "dataDeNascimento": "1999-08-21",
    "nacionalidade": "Croata",
    "posicao": "ADE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Vincent",
    "sobrenome": "Souza",
    "dataDeNascimento": "1996-06-09",
    "nacionalidade": "Camaronês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Andres",
    "sobrenome": "Henrique",
    "dataDeNascimento": "2002-03-22",
    "nacionalidade": "Espanhol",
    "posicao": "LD",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Luka",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1988-11-24",
    "nacionalidade": "Croata",
    "posicao": "ADE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Samuel",
    "sobrenome": "Silva",
    "dataDeNascimento": "1992-08-26",
    "nacionalidade": "Nigeriano",
    "posicao": "VOL",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Lorenzo",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2003-01-02",
    "nacionalidade": "Italiano",
    "posicao": "ATA",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1991-08-07",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2003-06-12",
    "nacionalidade": "Brasileiro",
    "posicao": "ATA",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Costa",
    "dataDeNascimento": "2003-02-21",
    "nacionalidade": "Camaronês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "John",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2003-08-15",
    "nacionalidade": "Nigeriano",
    "posicao": "LD",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Dias",
    "dataDeNascimento": "1993-08-27",
    "nacionalidade": "Argentino",
    "posicao": "ATA",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Andres",
    "sobrenome": "Martins",
    "dataDeNascimento": "1990-09-13",
    "nacionalidade": "Espanhol",
    "posicao": "LE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1997-03-01",
    "nacionalidade": "Uruguaio",
    "posicao": "VOL",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Gabriel",
    "sobrenome": "Barros",
    "dataDeNascimento": "1993-07-10",
    "nacionalidade": "Brasileiro",
    "posicao": "VOL",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "David",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "2004-02-27",
    "nacionalidade": "Espanhol",
    "posicao": "PD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1994-10-16",
    "nacionalidade": "Uruguaio",
    "posicao": "ADE",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "David",
    "sobrenome": "Barros",
    "dataDeNascimento": "2005-07-14",
    "nacionalidade": "Espanhol",
    "posicao": "PE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Gonzalo",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1986-11-01",
    "nacionalidade": "Argentino",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1994-09-19",
    "nacionalidade": "Alemão",
    "posicao": "GOL",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1988-04-22",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1986-09-28",
    "nacionalidade": "Chileno",
    "posicao": "PE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Silva",
    "dataDeNascimento": "1987-07-11",
    "nacionalidade": "Senegalês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Moreira",
    "dataDeNascimento": "2002-11-27",
    "nacionalidade": "Croata",
    "posicao": "ADE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Vincent",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1992-02-08",
    "nacionalidade": "Camaronês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Souza",
    "dataDeNascimento": "1994-05-19",
    "nacionalidade": "Português",
    "posicao": "ADE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1992-09-11",
    "nacionalidade": "Chileno",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1991-08-07",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "João",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "2000-10-25",
    "nacionalidade": "Brasileiro",
    "posicao": "PE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Dias",
    "dataDeNascimento": "1990-08-22",
    "nacionalidade": "Alemão",
    "posicao": "PD",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1992-11-26",
    "nacionalidade": "Senegalês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Luka",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1985-01-25",
    "nacionalidade": "Croata",
    "posicao": "MEI",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1993-05-25",
    "nacionalidade": "Camaronês",
    "posicao": "PE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Pablo",
    "sobrenome": "Silva",
    "dataDeNascimento": "1986-03-01",
    "nacionalidade": "Argentino",
    "posicao": "PE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Pablo",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1988-11-08",
    "nacionalidade": "Argentino",
    "posicao": "PE",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Barros",
    "dataDeNascimento": "2003-06-09",
    "nacionalidade": "Uruguaio",
    "posicao": "LD",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Matteo",
    "sobrenome": "Souza",
    "dataDeNascimento": "2002-09-12",
    "nacionalidade": "Italiano",
    "posicao": "GOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Santos",
    "dataDeNascimento": "1990-08-08",
    "nacionalidade": "Senegalês",
    "posicao": "PE",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Costa",
    "dataDeNascimento": "1991-12-05",
    "nacionalidade": "Português",
    "posicao": "PD",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1996-07-15",
    "nacionalidade": "Senegalês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Sadio",
    "sobrenome": "Santos",
    "dataDeNascimento": "2002-12-01",
    "nacionalidade": "Senegalês",
    "posicao": "LD",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Antoine",
    "sobrenome": "Costa",
    "dataDeNascimento": "1998-05-13",
    "nacionalidade": "Francês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Vincent",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1992-01-13",
    "nacionalidade": "Camaronês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1996-01-28",
    "nacionalidade": "Senegalês",
    "posicao": "LE",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Isco",
    "sobrenome": "Costa",
    "dataDeNascimento": "1995-08-07",
    "nacionalidade": "Espanhol",
    "posicao": "PE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Thiago",
    "sobrenome": "Silva",
    "dataDeNascimento": "1997-02-14",
    "nacionalidade": "Brasileiro",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2000-06-01",
    "nacionalidade": "Uruguaio",
    "posicao": "ATA",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1994-08-06",
    "nacionalidade": "Espanhol",
    "posicao": "PD",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Martins",
    "dataDeNascimento": "1991-11-15",
    "nacionalidade": "Camaronês",
    "posicao": "LD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Silva",
    "dataDeNascimento": "1997-11-20",
    "nacionalidade": "Francês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Gonçalo",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2004-03-23",
    "nacionalidade": "Português",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Santos",
    "dataDeNascimento": "2001-10-01",
    "nacionalidade": "Croata",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1985-08-15",
    "nacionalidade": "Camaronês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Costa",
    "dataDeNascimento": "1993-06-28",
    "nacionalidade": "Senegalês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Souza",
    "dataDeNascimento": "1985-07-15",
    "nacionalidade": "Português",
    "posicao": "LD",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Arturo",
    "sobrenome": "Santos",
    "dataDeNascimento": "1990-12-05",
    "nacionalidade": "Chileno",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Angel",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2000-07-01",
    "nacionalidade": "Argentino",
    "posicao": "MEI",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1994-10-21",
    "nacionalidade": "Croata",
    "posicao": "VOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1992-01-17",
    "nacionalidade": "Croata",
    "posicao": "MEI",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "João",
    "sobrenome": "Costa",
    "dataDeNascimento": "1994-04-22",
    "nacionalidade": "Brasileiro",
    "posicao": "ADE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Isco",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1997-05-10",
    "nacionalidade": "Espanhol",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1999-11-10",
    "nacionalidade": "Senegalês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Henrique",
    "dataDeNascimento": "2000-04-26",
    "nacionalidade": "Português",
    "posicao": "PE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2004-01-25",
    "nacionalidade": "Português",
    "posicao": "PE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Sadio",
    "sobrenome": "Costa",
    "dataDeNascimento": "1990-04-20",
    "nacionalidade": "Senegalês",
    "posicao": "LD",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Clinton",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1997-08-27",
    "nacionalidade": "Camaronês",
    "posicao": "PE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Santos",
    "dataDeNascimento": "1997-09-15",
    "nacionalidade": "Senegalês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1986-12-06",
    "nacionalidade": "Croata",
    "posicao": "ATA",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Matteo",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2005-09-03",
    "nacionalidade": "Italiano",
    "posicao": "GOL",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1990-05-28",
    "nacionalidade": "Croata",
    "posicao": "LE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1999-05-28",
    "nacionalidade": "Chileno",
    "posicao": "LE",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Costa",
    "dataDeNascimento": "1993-03-14",
    "nacionalidade": "Uruguaio",
    "posicao": "MEI",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1989-10-22",
    "nacionalidade": "Brasileiro",
    "posicao": "GOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "David",
    "sobrenome": "Dias",
    "dataDeNascimento": "1988-05-27",
    "nacionalidade": "Espanhol",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Gonzalo",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1997-05-02",
    "nacionalidade": "Argentino",
    "posicao": "MEI",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "David",
    "sobrenome": "Silva",
    "dataDeNascimento": "1988-04-12",
    "nacionalidade": "Espanhol",
    "posicao": "ATA",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Rigobert",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1994-05-18",
    "nacionalidade": "Camaronês",
    "posicao": "PD",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1989-05-08",
    "nacionalidade": "Português",
    "posicao": "ATA",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Andres",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1985-08-27",
    "nacionalidade": "Espanhol",
    "posicao": "GOL",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Matteo",
    "sobrenome": "Souza",
    "dataDeNascimento": "2004-12-22",
    "nacionalidade": "Italiano",
    "posicao": "GOL",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Clinton",
    "sobrenome": "Martins",
    "dataDeNascimento": "2001-03-18",
    "nacionalidade": "Camaronês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Santos",
    "dataDeNascimento": "2003-09-19",
    "nacionalidade": "Croata",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1997-05-03",
    "nacionalidade": "Uruguaio",
    "posicao": "LD",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Timo",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1996-12-05",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1989-10-22",
    "nacionalidade": "Uruguaio",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Santos",
    "dataDeNascimento": "1997-10-21",
    "nacionalidade": "Croata",
    "posicao": "ATA",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Silva",
    "dataDeNascimento": "1993-05-05",
    "nacionalidade": "Senegalês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Samuel",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1997-10-25",
    "nacionalidade": "Nigeriano",
    "posicao": "ADE",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Pedro",
    "sobrenome": "Barros",
    "dataDeNascimento": "2004-04-19",
    "nacionalidade": "Brasileiro",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Martins",
    "dataDeNascimento": "1992-12-27",
    "nacionalidade": "Italiano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "David",
    "sobrenome": "Costa",
    "dataDeNascimento": "2002-11-08",
    "nacionalidade": "Espanhol",
    "posicao": "PE",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Dias",
    "dataDeNascimento": "1987-08-09",
    "nacionalidade": "Francês",
    "posicao": "LE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Silva",
    "dataDeNascimento": "2000-08-24",
    "nacionalidade": "Alemão",
    "posicao": "ATA",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Gonçalo",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1994-06-12",
    "nacionalidade": "Português",
    "posicao": "ATA",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Santos",
    "dataDeNascimento": "1986-09-24",
    "nacionalidade": "Francês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Peter",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1996-05-23",
    "nacionalidade": "Nigeriano",
    "posicao": "LD",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Sebastián",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1999-06-03",
    "nacionalidade": "Uruguaio",
    "posicao": "GOL",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Antoine",
    "sobrenome": "Costa",
    "dataDeNascimento": "1990-09-20",
    "nacionalidade": "Francês",
    "posicao": "LE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1994-05-12",
    "nacionalidade": "Francês",
    "posicao": "PD",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Andres",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1985-08-10",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Sebastián",
    "sobrenome": "Souza",
    "dataDeNascimento": "1990-03-21",
    "nacionalidade": "Uruguaio",
    "posicao": "ATA",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1990-08-05",
    "nacionalidade": "Uruguaio",
    "posicao": "LD",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Silva",
    "dataDeNascimento": "2003-05-12",
    "nacionalidade": "Alemão",
    "posicao": "LD",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2000-08-23",
    "nacionalidade": "Francês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Gonçalo",
    "sobrenome": "Souza",
    "dataDeNascimento": "2003-08-18",
    "nacionalidade": "Português",
    "posicao": "PD",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Andres",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1991-09-10",
    "nacionalidade": "Espanhol",
    "posicao": "LD",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Martins",
    "dataDeNascimento": "1993-06-28",
    "nacionalidade": "Senegalês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Pablo",
    "sobrenome": "Dias",
    "dataDeNascimento": "1993-10-25",
    "nacionalidade": "Argentino",
    "posicao": "ATA",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Claudio",
    "sobrenome": "Silva",
    "dataDeNascimento": "2000-01-08",
    "nacionalidade": "Chileno",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Rafael",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1998-02-07",
    "nacionalidade": "Brasileiro",
    "posicao": "GOL",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1996-02-18",
    "nacionalidade": "Francês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Marco",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2004-03-11",
    "nacionalidade": "Italiano",
    "posicao": "PE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Angel",
    "sobrenome": "Silva",
    "dataDeNascimento": "1986-01-22",
    "nacionalidade": "Argentino",
    "posicao": "ATA",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "John",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1995-04-12",
    "nacionalidade": "Nigeriano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1991-08-16",
    "nacionalidade": "Nigeriano",
    "posicao": "PD",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Clinton",
    "sobrenome": "Santos",
    "dataDeNascimento": "2002-08-13",
    "nacionalidade": "Camaronês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1998-09-09",
    "nacionalidade": "Senegalês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1991-10-06",
    "nacionalidade": "Português",
    "posicao": "ATA",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Souza",
    "dataDeNascimento": "1992-08-09",
    "nacionalidade": "Português",
    "posicao": "PE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Dias",
    "dataDeNascimento": "2001-05-17",
    "nacionalidade": "Croata",
    "posicao": "ATA",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Henrique",
    "dataDeNascimento": "2004-04-01",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Isco",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1987-04-06",
    "nacionalidade": "Espanhol",
    "posicao": "LD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Angel",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2003-11-26",
    "nacionalidade": "Argentino",
    "posicao": "LE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "André",
    "sobrenome": "Dias",
    "dataDeNascimento": "2002-09-12",
    "nacionalidade": "Camaronês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "João",
    "sobrenome": "Souza",
    "dataDeNascimento": "2003-02-16",
    "nacionalidade": "Brasileiro",
    "posicao": "VOL",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1995-03-05",
    "nacionalidade": "Croata",
    "posicao": "PE",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Martins",
    "dataDeNascimento": "2000-02-12",
    "nacionalidade": "Francês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Costa",
    "dataDeNascimento": "1986-05-24",
    "nacionalidade": "Nigeriano",
    "posicao": "LE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "2001-08-19",
    "nacionalidade": "Italiano",
    "posicao": "MEI",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Moreira",
    "dataDeNascimento": "2001-11-12",
    "nacionalidade": "Brasileiro",
    "posicao": "PD",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Matteo",
    "sobrenome": "Souza",
    "dataDeNascimento": "2005-03-18",
    "nacionalidade": "Italiano",
    "posicao": "GOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Sebastián",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1985-05-28",
    "nacionalidade": "Uruguaio",
    "posicao": "VOL",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Marco",
    "sobrenome": "Souza",
    "dataDeNascimento": "1996-05-21",
    "nacionalidade": "Italiano",
    "posicao": "MEI",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Dias",
    "dataDeNascimento": "1992-09-20",
    "nacionalidade": "Croata",
    "posicao": "PE",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1988-07-20",
    "nacionalidade": "Senegalês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Matteo",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "2002-05-05",
    "nacionalidade": "Italiano",
    "posicao": "PD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1986-12-28",
    "nacionalidade": "Nigeriano",
    "posicao": "LD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1987-12-15",
    "nacionalidade": "Francês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1991-03-04",
    "nacionalidade": "Uruguaio",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Claudio",
    "sobrenome": "Martins",
    "dataDeNascimento": "1987-06-05",
    "nacionalidade": "Chileno",
    "posicao": "VOL",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Isco",
    "sobrenome": "Souza",
    "dataDeNascimento": "1997-06-15",
    "nacionalidade": "Espanhol",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Rigobert",
    "sobrenome": "Santos",
    "dataDeNascimento": "1990-11-13",
    "nacionalidade": "Camaronês",
    "posicao": "PE",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Silva",
    "dataDeNascimento": "1998-08-14",
    "nacionalidade": "Alemão",
    "posicao": "GOL",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Claudio",
    "sobrenome": "Martins",
    "dataDeNascimento": "1985-10-08",
    "nacionalidade": "Chileno",
    "posicao": "ADE",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Costa",
    "dataDeNascimento": "1996-09-15",
    "nacionalidade": "Alemão",
    "posicao": "MEI",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1989-07-11",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Gabriel",
    "sobrenome": "Souza",
    "dataDeNascimento": "1990-09-25",
    "nacionalidade": "Brasileiro",
    "posicao": "LE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Diego",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1995-02-12",
    "nacionalidade": "Uruguaio",
    "posicao": "PD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1996-08-27",
    "nacionalidade": "Francês",
    "posicao": "PD",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1989-01-09",
    "nacionalidade": "Francês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Silva",
    "dataDeNascimento": "1990-08-18",
    "nacionalidade": "Italiano",
    "posicao": "LD",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Arturo",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1987-11-09",
    "nacionalidade": "Chileno",
    "posicao": "PE",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2004-03-19",
    "nacionalidade": "Alemão",
    "posicao": "GOL",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Barros",
    "dataDeNascimento": "2003-10-21",
    "nacionalidade": "Uruguaio",
    "posicao": "PD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Silva",
    "dataDeNascimento": "1988-05-05",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Vincent",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1998-11-04",
    "nacionalidade": "Camaronês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Martins",
    "dataDeNascimento": "1986-03-25",
    "nacionalidade": "Senegalês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "João",
    "sobrenome": "Souza",
    "dataDeNascimento": "2002-07-21",
    "nacionalidade": "Português",
    "posicao": "LD",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Gomes",
    "dataDeNascimento": "2003-02-15",
    "nacionalidade": "Senegalês",
    "posicao": "PD",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1986-06-12",
    "nacionalidade": "Camaronês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Costa",
    "dataDeNascimento": "2005-10-21",
    "nacionalidade": "Chileno",
    "posicao": "LE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Barros",
    "dataDeNascimento": "2000-05-04",
    "nacionalidade": "Uruguaio",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Pablo",
    "sobrenome": "Souza",
    "dataDeNascimento": "2005-03-16",
    "nacionalidade": "Argentino",
    "posicao": "ADE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Dias",
    "dataDeNascimento": "1987-08-10",
    "nacionalidade": "Espanhol",
    "posicao": "GOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Gonzalo",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1991-02-06",
    "nacionalidade": "Argentino",
    "posicao": "PD",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Nicolas",
    "sobrenome": "Gomes",
    "dataDeNascimento": "2003-02-08",
    "nacionalidade": "Argentino",
    "posicao": "PE",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Lionel",
    "sobrenome": "Silva",
    "dataDeNascimento": "2001-01-10",
    "nacionalidade": "Argentino",
    "posicao": "LD",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1985-12-19",
    "nacionalidade": "Francês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1998-10-13",
    "nacionalidade": "Chileno",
    "posicao": "VOL",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Angel",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1998-06-09",
    "nacionalidade": "Argentino",
    "posicao": "PD",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Matteo",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1992-02-26",
    "nacionalidade": "Italiano",
    "posicao": "ADE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Dias",
    "dataDeNascimento": "1985-02-08",
    "nacionalidade": "Croata",
    "posicao": "LE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1998-03-14",
    "nacionalidade": "Senegalês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Souza",
    "dataDeNascimento": "2001-06-06",
    "nacionalidade": "Croata",
    "posicao": "LE",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1999-10-28",
    "nacionalidade": "Uruguaio",
    "posicao": "PE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Silva",
    "dataDeNascimento": "1998-02-07",
    "nacionalidade": "Francês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Dias",
    "dataDeNascimento": "1986-07-15",
    "nacionalidade": "Senegalês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2002-02-26",
    "nacionalidade": "Italiano",
    "posicao": "LD",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Samuel",
    "sobrenome": "Barros",
    "dataDeNascimento": "1986-03-03",
    "nacionalidade": "Nigeriano",
    "posicao": "LD",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1992-02-28",
    "nacionalidade": "Croata",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "2003-06-11",
    "nacionalidade": "Francês",
    "posicao": "LD",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2004-04-02",
    "nacionalidade": "Croata",
    "posicao": "GOL",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1994-12-20",
    "nacionalidade": "Senegalês",
    "posicao": "LE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Souza",
    "dataDeNascimento": "1999-04-04",
    "nacionalidade": "Uruguaio",
    "posicao": "PD",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1996-10-13",
    "nacionalidade": "Alemão",
    "posicao": "PD",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Ruben",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2004-07-27",
    "nacionalidade": "Português",
    "posicao": "GOL",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Dias",
    "dataDeNascimento": "1986-06-21",
    "nacionalidade": "Francês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Dias",
    "dataDeNascimento": "1994-10-04",
    "nacionalidade": "Espanhol",
    "posicao": "PE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Marco",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1997-05-05",
    "nacionalidade": "Italiano",
    "posicao": "VOL",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Lorenzo",
    "sobrenome": "Santos",
    "dataDeNascimento": "1995-10-23",
    "nacionalidade": "Italiano",
    "posicao": "ADE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1989-08-19",
    "nacionalidade": "Francês",
    "posicao": "LE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Souza",
    "dataDeNascimento": "2004-03-27",
    "nacionalidade": "Senegalês",
    "posicao": "PD",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "John",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1997-10-18",
    "nacionalidade": "Nigeriano",
    "posicao": "LD",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Pablo",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1995-08-01",
    "nacionalidade": "Argentino",
    "posicao": "GOL",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Lionel",
    "sobrenome": "Dias",
    "dataDeNascimento": "1991-08-05",
    "nacionalidade": "Argentino",
    "posicao": "LE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Gomes",
    "dataDeNascimento": "2002-05-06",
    "nacionalidade": "Nigeriano",
    "posicao": "LE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Costa",
    "dataDeNascimento": "2003-10-09",
    "nacionalidade": "Chileno",
    "posicao": "VOL",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Dias",
    "dataDeNascimento": "1989-01-23",
    "nacionalidade": "Croata",
    "posicao": "PE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2004-01-14",
    "nacionalidade": "Uruguaio",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Samuel",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "2000-06-08",
    "nacionalidade": "Nigeriano",
    "posicao": "VOL",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Silva",
    "dataDeNascimento": "1993-06-24",
    "nacionalidade": "Chileno",
    "posicao": "LD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Arturo",
    "sobrenome": "Barros",
    "dataDeNascimento": "2000-06-27",
    "nacionalidade": "Chileno",
    "posicao": "ATA",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Souza",
    "dataDeNascimento": "1985-02-09",
    "nacionalidade": "Croata",
    "posicao": "LE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "João",
    "sobrenome": "Silva",
    "dataDeNascimento": "1988-05-14",
    "nacionalidade": "Português",
    "posicao": "MEI",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Diego",
    "sobrenome": "Martins",
    "dataDeNascimento": "1996-07-09",
    "nacionalidade": "Uruguaio",
    "posicao": "LD",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1993-04-22",
    "nacionalidade": "Francês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Dias",
    "dataDeNascimento": "1999-03-20",
    "nacionalidade": "Croata",
    "posicao": "LD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Matteo",
    "sobrenome": "Dias",
    "dataDeNascimento": "1985-04-25",
    "nacionalidade": "Italiano",
    "posicao": "VOL",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1985-10-16",
    "nacionalidade": "Alemão",
    "posicao": "ATA",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Gonçalo",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "2001-10-14",
    "nacionalidade": "Português",
    "posicao": "MEI",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2004-04-13",
    "nacionalidade": "Português",
    "posicao": "PE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Costa",
    "dataDeNascimento": "2001-04-07",
    "nacionalidade": "Croata",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Silva",
    "dataDeNascimento": "1993-04-20",
    "nacionalidade": "Nigeriano",
    "posicao": "MEI",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1989-08-14",
    "nacionalidade": "Francês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Silva",
    "dataDeNascimento": "2004-07-19",
    "nacionalidade": "Chileno",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Sadio",
    "sobrenome": "Costa",
    "dataDeNascimento": "2001-11-19",
    "nacionalidade": "Senegalês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Rigobert",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1985-11-18",
    "nacionalidade": "Camaronês",
    "posicao": "LD",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Timo",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1992-01-18",
    "nacionalidade": "Alemão",
    "posicao": "LD",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1995-07-26",
    "nacionalidade": "Uruguaio",
    "posicao": "MEI",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Santos",
    "dataDeNascimento": "1991-12-17",
    "nacionalidade": "Alemão",
    "posicao": "PE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2004-06-23",
    "nacionalidade": "Italiano",
    "posicao": "ADE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1997-06-18",
    "nacionalidade": "Croata",
    "posicao": "GOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Arturo",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1997-03-07",
    "nacionalidade": "Chileno",
    "posicao": "PE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Angel",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1990-01-09",
    "nacionalidade": "Argentino",
    "posicao": "LE",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Andres",
    "sobrenome": "Martins",
    "dataDeNascimento": "1989-07-01",
    "nacionalidade": "Espanhol",
    "posicao": "PE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Lionel",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1996-01-20",
    "nacionalidade": "Argentino",
    "posicao": "PE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1993-08-20",
    "nacionalidade": "Croata",
    "posicao": "GOL",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1997-12-15",
    "nacionalidade": "Nigeriano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Gonzalo",
    "sobrenome": "Santos",
    "dataDeNascimento": "1995-04-04",
    "nacionalidade": "Argentino",
    "posicao": "MEI",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Peter",
    "sobrenome": "Santos",
    "dataDeNascimento": "1998-12-07",
    "nacionalidade": "Nigeriano",
    "posicao": "MEI",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Silva",
    "dataDeNascimento": "2002-12-19",
    "nacionalidade": "Alemão",
    "posicao": "LD",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Santos",
    "dataDeNascimento": "2001-02-09",
    "nacionalidade": "Italiano",
    "posicao": "PE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "João",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1985-07-16",
    "nacionalidade": "Brasileiro",
    "posicao": "MEI",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1994-02-08",
    "nacionalidade": "Senegalês",
    "posicao": "LE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Silva",
    "dataDeNascimento": "1999-10-20",
    "nacionalidade": "Chileno",
    "posicao": "VOL",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "João",
    "sobrenome": "Costa",
    "dataDeNascimento": "1985-08-24",
    "nacionalidade": "Português",
    "posicao": "PE",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Sadio",
    "sobrenome": "Moreira",
    "dataDeNascimento": "2005-12-02",
    "nacionalidade": "Senegalês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Barros",
    "dataDeNascimento": "1990-11-21",
    "nacionalidade": "Argentino",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Thiago",
    "sobrenome": "Santos",
    "dataDeNascimento": "2000-04-23",
    "nacionalidade": "Brasileiro",
    "posicao": "PE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Gonçalo",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1998-09-07",
    "nacionalidade": "Português",
    "posicao": "PE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "André",
    "sobrenome": "Santos",
    "dataDeNascimento": "2002-06-14",
    "nacionalidade": "Camaronês",
    "posicao": "LD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Lionel",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1987-06-09",
    "nacionalidade": "Argentino",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Isco",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1991-09-26",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Claudio",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1988-07-27",
    "nacionalidade": "Chileno",
    "posicao": "GOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1995-11-21",
    "nacionalidade": "Senegalês",
    "posicao": "LD",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1992-01-26",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1992-04-20",
    "nacionalidade": "Croata",
    "posicao": "LE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Luka",
    "sobrenome": "Martins",
    "dataDeNascimento": "1993-11-02",
    "nacionalidade": "Croata",
    "posicao": "LD",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Barros",
    "dataDeNascimento": "1994-04-07",
    "nacionalidade": "Senegalês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Gonzalo",
    "sobrenome": "Moreira",
    "dataDeNascimento": "2004-03-23",
    "nacionalidade": "Argentino",
    "posicao": "ADE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Costa",
    "dataDeNascimento": "1996-04-27",
    "nacionalidade": "Chileno",
    "posicao": "LE",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Claudio",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1996-06-19",
    "nacionalidade": "Chileno",
    "posicao": "PD",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Barros",
    "dataDeNascimento": "2000-04-03",
    "nacionalidade": "Chileno",
    "posicao": "LE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "John",
    "sobrenome": "Silva",
    "dataDeNascimento": "1994-03-19",
    "nacionalidade": "Nigeriano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Marco",
    "sobrenome": "Barros",
    "dataDeNascimento": "2004-04-01",
    "nacionalidade": "Italiano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Sebastián",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1992-04-21",
    "nacionalidade": "Uruguaio",
    "posicao": "PD",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1995-07-22",
    "nacionalidade": "Uruguaio",
    "posicao": "PD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Barros",
    "dataDeNascimento": "1999-05-01",
    "nacionalidade": "Italiano",
    "posicao": "LE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1996-04-27",
    "nacionalidade": "Argentino",
    "posicao": "PD",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Souza",
    "dataDeNascimento": "2005-12-27",
    "nacionalidade": "Chileno",
    "posicao": "PE",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1987-02-23",
    "nacionalidade": "Italiano",
    "posicao": "LD",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Samuel",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2002-07-12",
    "nacionalidade": "Nigeriano",
    "posicao": "LE",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Edinson",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1998-07-01",
    "nacionalidade": "Uruguaio",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Ivan",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1990-05-05",
    "nacionalidade": "Croata",
    "posicao": "GOL",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1988-05-11",
    "nacionalidade": "Alemão",
    "posicao": "ATA",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Costa",
    "dataDeNascimento": "1992-05-04",
    "nacionalidade": "Nigeriano",
    "posicao": "ATA",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1998-08-04",
    "nacionalidade": "Senegalês",
    "posicao": "PE",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "Luka",
    "sobrenome": "Souza",
    "dataDeNascimento": "1985-05-06",
    "nacionalidade": "Croata",
    "posicao": "MEI",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Silva",
    "dataDeNascimento": "1992-03-13",
    "nacionalidade": "Argentino",
    "posicao": "VOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1987-11-13",
    "nacionalidade": "Nigeriano",
    "posicao": "VOL",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Claudio",
    "sobrenome": "Souza",
    "dataDeNascimento": "1993-07-27",
    "nacionalidade": "Chileno",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1991-11-16",
    "nacionalidade": "Senegalês",
    "posicao": "PE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Nicolas",
    "sobrenome": "Gomes",
    "dataDeNascimento": "2001-04-12",
    "nacionalidade": "Argentino",
    "posicao": "PD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Gonçalo",
    "sobrenome": "Santos",
    "dataDeNascimento": "2002-11-23",
    "nacionalidade": "Português",
    "posicao": "LE",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1985-08-03",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Niklas",
    "sobrenome": "Moreira",
    "dataDeNascimento": "2003-11-16",
    "nacionalidade": "Alemão",
    "posicao": "PE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1996-04-24",
    "nacionalidade": "Brasileiro",
    "posicao": "VOL",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "David",
    "sobrenome": "Barros",
    "dataDeNascimento": "1999-02-03",
    "nacionalidade": "Espanhol",
    "posicao": "GOL",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Samuel",
    "sobrenome": "Silva",
    "dataDeNascimento": "1996-08-04",
    "nacionalidade": "Nigeriano",
    "posicao": "PE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Isco",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2004-10-01",
    "nacionalidade": "Espanhol",
    "posicao": "MEI",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Mario",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2004-09-07",
    "nacionalidade": "Croata",
    "posicao": "GOL",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Antoine",
    "sobrenome": "Santos",
    "dataDeNascimento": "1999-07-15",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Barros",
    "dataDeNascimento": "1994-06-05",
    "nacionalidade": "Português",
    "posicao": "VOL",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Peter",
    "sobrenome": "Costa",
    "dataDeNascimento": "1985-01-25",
    "nacionalidade": "Nigeriano",
    "posicao": "LE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Dias",
    "dataDeNascimento": "1995-05-25",
    "nacionalidade": "Nigeriano",
    "posicao": "ADE",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "John",
    "sobrenome": "Costa",
    "dataDeNascimento": "2004-05-05",
    "nacionalidade": "Nigeriano",
    "posicao": "MEI",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Souza",
    "dataDeNascimento": "2002-10-26",
    "nacionalidade": "Chileno",
    "posicao": "LD",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Hugo",
    "sobrenome": "Barros",
    "dataDeNascimento": "2004-10-17",
    "nacionalidade": "Francês",
    "posicao": "LE",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Diego",
    "sobrenome": "Costa",
    "dataDeNascimento": "2000-09-12",
    "nacionalidade": "Uruguaio",
    "posicao": "ATA",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Moussa",
    "sobrenome": "Barros",
    "dataDeNascimento": "1999-04-28",
    "nacionalidade": "Senegalês",
    "posicao": "GOL",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Pablo",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1988-11-21",
    "nacionalidade": "Argentino",
    "posicao": "LD",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Thiago",
    "sobrenome": "Gomes",
    "dataDeNascimento": "2001-06-11",
    "nacionalidade": "Brasileiro",
    "posicao": "ADE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Silva",
    "dataDeNascimento": "2003-12-26",
    "nacionalidade": "Alemão",
    "posicao": "PD",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Henrique",
    "dataDeNascimento": "1995-10-28",
    "nacionalidade": "Francês",
    "posicao": "LE",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "John",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1987-02-11",
    "nacionalidade": "Nigeriano",
    "posicao": "PD",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1986-01-04",
    "nacionalidade": "Chileno",
    "posicao": "PD",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1988-05-28",
    "nacionalidade": "Nigeriano",
    "posicao": "GOL",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1985-02-16",
    "nacionalidade": "Português",
    "posicao": "VOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Santos",
    "dataDeNascimento": "1997-10-14",
    "nacionalidade": "Alemão",
    "posicao": "MEI",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Dias",
    "dataDeNascimento": "1991-11-19",
    "nacionalidade": "Francês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Timo",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1998-01-26",
    "nacionalidade": "Alemão",
    "posicao": "PD",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1990-08-19",
    "nacionalidade": "Alemão",
    "posicao": "LE",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1989-12-11",
    "nacionalidade": "Alemão",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Silva",
    "dataDeNascimento": "1987-12-17",
    "nacionalidade": "Chileno",
    "posicao": "ADE",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Niklas",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2004-10-20",
    "nacionalidade": "Alemão",
    "posicao": "ADE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Isco",
    "sobrenome": "Silva",
    "dataDeNascimento": "1997-12-06",
    "nacionalidade": "Espanhol",
    "posicao": "MEI",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1993-08-05",
    "nacionalidade": "Chileno",
    "posicao": "LD",
    "clube": {
      "clubeId": 3
    }
  },
  {
    "nome": "Ahmed",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1986-12-06",
    "nacionalidade": "Nigeriano",
    "posicao": "ATA",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Andres",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1992-01-09",
    "nacionalidade": "Espanhol",
    "posicao": "PE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1988-02-28",
    "nacionalidade": "Senegalês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Giovanni",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1995-07-21",
    "nacionalidade": "Italiano",
    "posicao": "PE",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Clinton",
    "sobrenome": "Dias",
    "dataDeNascimento": "1991-11-10",
    "nacionalidade": "Camaronês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2005-02-06",
    "nacionalidade": "Nigeriano",
    "posicao": "PD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Costa",
    "dataDeNascimento": "1998-09-14",
    "nacionalidade": "Francês",
    "posicao": "LE",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1991-05-09",
    "nacionalidade": "Uruguaio",
    "posicao": "LD",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "2003-10-10",
    "nacionalidade": "Senegalês",
    "posicao": "LD",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1994-12-18",
    "nacionalidade": "Alemão",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Bernardo",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1992-03-10",
    "nacionalidade": "Português",
    "posicao": "VOL",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Lionel",
    "sobrenome": "Silva",
    "dataDeNascimento": "2000-04-12",
    "nacionalidade": "Argentino",
    "posicao": "LE",
    "clube": {
      "clubeId": 2
    }
  },
  {
    "nome": "Jean",
    "sobrenome": "Santos",
    "dataDeNascimento": "2001-06-18",
    "nacionalidade": "Chileno",
    "posicao": "GOL",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1996-11-14",
    "nacionalidade": "Alemão",
    "posicao": "LE",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1997-03-06",
    "nacionalidade": "Chileno",
    "posicao": "LE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Gonçalo",
    "sobrenome": "Silva",
    "dataDeNascimento": "1999-07-12",
    "nacionalidade": "Português",
    "posicao": "PE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1986-04-01",
    "nacionalidade": "Croata",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "1994-03-27",
    "nacionalidade": "Brasileiro",
    "posicao": "PE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Alexis",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1986-03-10",
    "nacionalidade": "Chileno",
    "posicao": "MEI",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Thiago",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1988-11-13",
    "nacionalidade": "Brasileiro",
    "posicao": "PD",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Thiago",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1999-03-22",
    "nacionalidade": "Brasileiro",
    "posicao": "ATA",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Lorenzo",
    "sobrenome": "Santos",
    "dataDeNascimento": "1987-06-19",
    "nacionalidade": "Italiano",
    "posicao": "LE",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1993-09-17",
    "nacionalidade": "Espanhol",
    "posicao": "MEI",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Santos",
    "dataDeNascimento": "2000-12-23",
    "nacionalidade": "Alemão",
    "posicao": "ATA",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Lukas",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1993-11-25",
    "nacionalidade": "Alemão",
    "posicao": "MEI",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Henrique",
    "dataDeNascimento": "2005-08-17",
    "nacionalidade": "Espanhol",
    "posicao": "LD",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Santos",
    "dataDeNascimento": "1989-05-20",
    "nacionalidade": "Senegalês",
    "posicao": "PE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Victor",
    "sobrenome": "Souza",
    "dataDeNascimento": "2001-04-04",
    "nacionalidade": "Nigeriano",
    "posicao": "LE",
    "clube": {
      "clubeId": 8
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Santos",
    "dataDeNascimento": "1985-06-01",
    "nacionalidade": "Francês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Dias",
    "dataDeNascimento": "1988-11-22",
    "nacionalidade": "Português",
    "posicao": "PD",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Silva",
    "dataDeNascimento": "1998-07-10",
    "nacionalidade": "Espanhol",
    "posicao": "PE",
    "clube": {
      "clubeId": 6
    }
  },
  {
    "nome": "Nicolas",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2001-08-24",
    "nacionalidade": "Argentino",
    "posicao": "GOL",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Kalidou",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1998-10-11",
    "nacionalidade": "Senegalês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 9
    }
  },
  {
    "nome": "Antoine",
    "sobrenome": "Souza",
    "dataDeNascimento": "1993-07-08",
    "nacionalidade": "Francês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Dias",
    "dataDeNascimento": "1988-07-05",
    "nacionalidade": "Uruguaio",
    "posicao": "PE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Souza",
    "dataDeNascimento": "2003-01-12",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Timo",
    "sobrenome": "Oliveira",
    "dataDeNascimento": "1990-08-01",
    "nacionalidade": "Alemão",
    "posicao": "GOL",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Peter",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1996-05-11",
    "nacionalidade": "Nigeriano",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "André",
    "sobrenome": "Martins",
    "dataDeNascimento": "2005-10-13",
    "nacionalidade": "Camaronês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Silva",
    "dataDeNascimento": "2001-07-01",
    "nacionalidade": "Senegalês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Nicolas",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1991-03-07",
    "nacionalidade": "Argentino",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 10
    }
  },
  {
    "nome": "Pablo",
    "sobrenome": "Dias",
    "dataDeNascimento": "2003-07-04",
    "nacionalidade": "Argentino",
    "posicao": "LE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Costa",
    "dataDeNascimento": "1998-06-14",
    "nacionalidade": "Chileno",
    "posicao": "LD",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1991-02-13",
    "nacionalidade": "Alemão",
    "posicao": "PE",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Antoine",
    "sobrenome": "Gomes",
    "dataDeNascimento": "1997-09-10",
    "nacionalidade": "Francês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Cristiano",
    "sobrenome": "Santos",
    "dataDeNascimento": "1990-07-05",
    "nacionalidade": "Português",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Kylian",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2002-07-24",
    "nacionalidade": "Francês",
    "posicao": "ADE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Pedro",
    "sobrenome": "Fernandez",
    "dataDeNascimento": "2005-02-05",
    "nacionalidade": "Brasileiro",
    "posicao": "ADE",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Ante",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1986-08-06",
    "nacionalidade": "Croata",
    "posicao": "VOL",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Lorenzo",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2005-05-17",
    "nacionalidade": "Italiano",
    "posicao": "LE",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Rigobert",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "2001-10-22",
    "nacionalidade": "Camaronês",
    "posicao": "LD",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "André",
    "sobrenome": "Gomes",
    "dataDeNascimento": "2001-09-25",
    "nacionalidade": "Camaronês",
    "posicao": "LE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Luis",
    "sobrenome": "Costa",
    "dataDeNascimento": "2001-09-08",
    "nacionalidade": "Uruguaio",
    "posicao": "PE",
    "clube": {
      "clubeId": 11
    }
  },
  {
    "nome": "Alessandro",
    "sobrenome": "Souza",
    "dataDeNascimento": "1999-06-06",
    "nacionalidade": "Italiano",
    "posicao": "ATA",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Souza",
    "dataDeNascimento": "1992-10-03",
    "nacionalidade": "Francês",
    "posicao": "ATA",
    "clube": {
      "clubeId": 7
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "1999-02-28",
    "nacionalidade": "Alemão",
    "posicao": "VOL",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Lucas",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2005-02-28",
    "nacionalidade": "Brasileiro",
    "posicao": "PE",
    "clube": {
      "clubeId": 12
    }
  },
  {
    "nome": "Mats",
    "sobrenome": "Costa",
    "dataDeNascimento": "1998-01-03",
    "nacionalidade": "Alemão",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 20
    }
  },
  {
    "nome": "Sergio",
    "sobrenome": "Barros",
    "dataDeNascimento": "1991-04-01",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Domagoj",
    "sobrenome": "Ferreira",
    "dataDeNascimento": "1999-05-23",
    "nacionalidade": "Croata",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 17
    }
  },
  {
    "nome": "Sadio",
    "sobrenome": "Silva",
    "dataDeNascimento": "1998-10-16",
    "nacionalidade": "Senegalês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 4
    }
  },
  {
    "nome": "Gabriel",
    "sobrenome": "Souza",
    "dataDeNascimento": "1990-06-05",
    "nacionalidade": "Brasileiro",
    "posicao": "LD",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Jonas",
    "sobrenome": "Almeida",
    "dataDeNascimento": "1987-10-01",
    "nacionalidade": "Alemão",
    "posicao": "PD",
    "clube": {
      "clubeId": 14
    }
  },
  {
    "nome": "Maxi",
    "sobrenome": "Almeida",
    "dataDeNascimento": "2003-09-09",
    "nacionalidade": "Uruguaio",
    "posicao": "ATA",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Jordi",
    "sobrenome": "Santos",
    "dataDeNascimento": "1996-02-26",
    "nacionalidade": "Espanhol",
    "posicao": "ADE",
    "clube": {
      "clubeId": 1
    }
  },
  {
    "nome": "Cheikhou",
    "sobrenome": "Pereira",
    "dataDeNascimento": "2002-12-08",
    "nacionalidade": "Senegalês",
    "posicao": "LD",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Mauricio",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1993-02-24",
    "nacionalidade": "Chileno",
    "posicao": "LE",
    "clube": {
      "clubeId": 5
    }
  },
  {
    "nome": "Diego",
    "sobrenome": "Barros",
    "dataDeNascimento": "2003-07-14",
    "nacionalidade": "Uruguaio",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 19
    }
  },
  {
    "nome": "Niklas",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1995-06-10",
    "nacionalidade": "Alemão",
    "posicao": "PE",
    "clube": {
      "clubeId": 16
    }
  },
  {
    "nome": "Olivier",
    "sobrenome": "Pereira",
    "dataDeNascimento": "1996-06-28",
    "nacionalidade": "Francês",
    "posicao": "ZAG",
    "clube": {
      "clubeId": 13
    }
  },
  {
    "nome": "Lionel",
    "sobrenome": "Rodriguez",
    "dataDeNascimento": "2002-04-06",
    "nacionalidade": "Argentino",
    "posicao": "MEI",
    "clube": {
      "clubeId": 15
    }
  },
  {
    "nome": "André",
    "sobrenome": "Moreira",
    "dataDeNascimento": "1991-12-19",
    "nacionalidade": "Camaronês",
    "posicao": "VOL",
    "clube": {
      "clubeId": 18
    }
  },
  {
    "nome": "Idrissa",
    "sobrenome": "Silva",
    "dataDeNascimento": "1995-06-20",
    "nacionalidade": "Senegalês",
    "posicao": "MEI",
    "clube": {
      "clubeId": 8
    }
  }
]