POST http://localhost:8080/api/atleta/adicionarr
Content-Type: application/json

[
  
  {
    "nome": "Lucas",
    "sobrenome": "Silva",
    "dataDeNascimento": "1995-03-10",
    "nacionalidade": "brasileiro",
    "posicao": "ATA",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 3 }
  },
  {
    "nome": "Carlos",
    "sobrenome": "Menezes",
    "dataDeNascimento": "1998-07-15",
    "nacionalidade": "argentino",
    "posicao": "MEI",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 2 }
  },
  {
    "nome": "Kenji",
    "sobrenome": "Tanaka",
    "dataDeNascimento": "1999-09-25",
    "nacionalidade": "japonês",
    "posicao": "VOL",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 4 }
  },
  {
    "nome": "André",
    "sobrenome": "Costa",
    "dataDeNascimento": "1994-11-02",
    "nacionalidade": "brasileiro",
    "posicao": "ADE",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 1 }
  },
  {
    "nome": "Mohamed",
    "sobrenome": "Salah",
    "dataDeNascimento": "1992-06-15",
    "nacionalidade": "egípcio",
    "posicao": "ATA",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 7 }
  },
  {
    "nome": "Jean",
    "sobrenome": "Dupont",
    "dataDeNascimento": "1997-01-30",
    "nacionalidade": "francês",
    "posicao": "MEI",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 5 }
  },
  {
    "nome": "Liam",
    "sobrenome": "Smith",
    "dataDeNascimento": "2000-12-10",
    "nacionalidade": "inglês",
    "posicao": "GOL",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 1 }
  },
  {
    "nome": "Pedro",
    "sobrenome": "Alvarez",
    "dataDeNascimento": "1993-04-17",
    "nacionalidade": "espanhol",
    "posicao": "ZAG",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 3 }
  },
  {
    "nome": "Nikolai",
    "sobrenome": "Ivanov",
    "dataDeNascimento": "1996-08-08",
    "nacionalidade": "russo",
    "posicao": "VOL",
    "gol": 0,
    "assistencia": 0,
    "clube": { "clubeId": 2 }
  }
]
