-- Módulo Centro Tático: configuração pessoal por usuário + clube

CREATE TABLE IF NOT EXISTS tatica_usuario_clube (
    "taticaUsuarioClubeId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    clube_id BIGINT NOT NULL,
    "taticaFormacao" VARCHAR(20) NOT NULL DEFAULT '4-4-2',
    "taticaAnotacoes" TEXT,
    "capitaoAtletaId" BIGINT,
    "batedorPenaltisAtletaId" BIGINT,
    "batedorFaltaAtletaId" BIGINT,
    "batedorEscanteioEsquerdoAtletaId" BIGINT,
    "batedorEscanteioDireitoAtletaId" BIGINT,
    "taticaDataUltimaAtualizacao" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tatica_usuario_clube UNIQUE (user_id, clube_id),
    CONSTRAINT fk_tatica_usuario FOREIGN KEY (user_id) REFERENCES usuario ("userId"),
    CONSTRAINT fk_tatica_clube FOREIGN KEY (clube_id) REFERENCES clube ("clubeId")
);

CREATE TABLE IF NOT EXISTS tatica_jogador (
    "taticaJogadorId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tatica_usuario_clube_id BIGINT NOT NULL,
    atleta_id BIGINT NOT NULL,
    "taticaJogadorTipo" VARCHAR(20) NOT NULL,
    "taticaJogadorPosicaoX" DOUBLE,
    "taticaJogadorPosicaoY" DOUBLE,
    "taticaJogadorOrdemReserva" INTEGER,
    CONSTRAINT uk_tatica_jogador_atleta UNIQUE (tatica_usuario_clube_id, atleta_id),
    CONSTRAINT fk_tatica_jogador_tatica FOREIGN KEY (tatica_usuario_clube_id) REFERENCES tatica_usuario_clube ("taticaUsuarioClubeId"),
    CONSTRAINT fk_tatica_jogador_atleta FOREIGN KEY (atleta_id) REFERENCES atleta ("atletaId")
);
